name: inapi_core_sdk
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.11.6+hotfix.1
  socket_io_client: ^2.0.3+1
  mediasoup_client_flutter:
    git:
      url: https://github.com/shukill/mediasoup-client-flutter.git
      ref: main 
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
